---
title: "p8105_hw3_zz3168"
author: "Zixuan Zhang"
date: "2023-10-10"
output: github_document
---


```{r}
library(p8105.datasets)
data("instacart")
library(tidyverse)
library(p8105.datasets)
data("brfss_smart2010")
library(ggridges)
library(patchwork)

```

### Problem 1


```{r}



knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Problem 2
```{r}
clean_data = 
  brfss_smart2010 |> 
  janitor::clean_names() |> 
  filter(topic == "Overall Health", 
         response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) |> 
  mutate(
    response =  factor(response, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"))
  ) |> 
  arrange(response)

```


```{r}
brfss_state_2002 = 
  clean_data |> 
  filter(year == "2002") |> 
  group_by(locationabbr) |> 
  summarize(location_num = n_distinct(locationdesc)) |> 
  filter(location_num >= 7 )

brfss_state_2010 = 
  clean_data |> 
  filter(year == "2010") |> 
  group_by(locationabbr) |> 
  summarize(location_num = n_distinct(locationdesc)) |> 
  filter(location_num >= 7 )
  
  
```


#construct a dataset
```{r}
dataset_exce =
  clean_data |> 
  filter(response == "Excellent") |> 
  group_by(year, locationabbr) |>
  summarize(avg_value = mean(data_value, na.rm = TRUE))


ggplot(
  dataset_exce, 
  aes(
    x = year, 
    y = avg_value, 
    group = locationabbr, 
    color = locationabbr )) +
  geom_point() +
  geom_line() +
  labs(
    title = "Average Value of 'Excellent' Responses ", 
    x = "Year",
    y = "Average Value") +
  theme_minimal()

  
   
```


#two-panel plot 
```{r}
clean_data |> 
  filter(year %in% c(2006, 2010), locationabbr == "NY") |> 
  ggplot(aes(x = response, y = data_value, fill = response)) +
  geom_boxplot() +
  facet_grid(~year)
```


### Problem 3

```{r}
parti_data =
  read_csv("data/nhanes_covar.csv", skip = 4) |> 
  janitor::clean_names() |> 
  filter(
    age >= 21,
    is.na(bmi) == FALSE,
    is.na(education) == FALSE
  ) |> 
  mutate(
    sex = 
      case_match(
        sex,
        1 ~ "male",
        2 ~ "female"),
    sex = as.factor(sex),
    education = 
      case_match(
        education, 
        1 ~ "Less than high school",
        2 ~ "High school equivalent",
        3 ~ "More than high school"),
    education = as.factor(education)
      )
        
      


  

accel_data = 
  read_csv("data/nhanes_accel.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    min1:min1440,
    names_to = "number time",
    values_to = "activity time",
    names_prefix = "min"
  )
  

nahanes_merge = 
  left_join(parti_data, accel_data, by = "seqn")
```


